# Base image
FROM python:3.11-slim

# Set the working directory
WORKDIR /surveyapp

# Copy and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy only essential files
COPY app/ app/
COPY config.py .

# Set environment variables
ENV FLASK_APP=app:create_app
ENV FLASK_RUN_HOST=0.0.0.0
ENV FLASK_ENV=production
# Expose the Flask port
EXPOSE 5000

# Run the Flask app
CMD ["flask", "run"]