"""Add phase1_completed to Organization table

Revision ID: 2dcaba1849cd
Revises: c00992278c3f
Create Date: 2025-09-30 11:46:26.642100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dcaba1849cd'
down_revision = 'c00992278c3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phase1_completed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_column('phase1_completed')

    # ### end Alembic commands ###