"""Add computed_archetype field to questionnaire_responses

Revision ID: 86e9a1987709
Revises: 
Create Date: 2025-09-27 23:05:12.010799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86e9a1987709'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questionnaire_responses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('computed_archetype', sa.Text(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)

    with op.batch_alter_table('questionnaire_responses', schema=None) as batch_op:
        batch_op.drop_column('computed_archetype')

    # ### end Alembic commands ###