"""Initial migration.

Revision ID: 9cbcb251f482
Revises: 
Create Date: 2024-08-10 23:47:23.919775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cbcb251f482'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_cluster',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_cluster_name', sa.String(length=255), nullable=False),
    sa.Column('role_cluster_description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_cluster_name')
    )
    op.drop_table('roles_clusters')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles_clusters',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('role_cluster_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('role_cluster_description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='roles_clusters_pkey'),
    sa.UniqueConstraint('role_cluster_name', name='roles_clusters_role_cluster_name_key')
    )
    op.drop_table('role_cluster')
    # ### end Alembic commands ###
